#!/usr/bin/env python3
"""Figure: the live aim loop, recovered from telemetry (id `camera-control-law`).

Renders `docs/assets/camera-control-law.svg` from `pvpbot-flight.jsonl`, the
per-tick telemetry the deploy loop appends during a live run. That file is
gitignored, so a fresh clone will not have it and this script exits with a
clear message instead of a traceback.

What is plotted
---------------
LEFT  the perceived yaw error to the enemy centre (`obs[22] * 180`, degrees)
      against the camera delta the loop actually commanded that tick
      (`action[5]` mapped through `CAMERA_BINS` from `pvpbot/spec.py`), as a
      log-count hexbin, with the analytic control law read out of
      `pvpbot/deploy/loop.py:848-849` drawn on top as a step function:
      the nearest camera bin to `clip(0.7 * err_deg, -25, +25)`.
RIGHT overlaid histograms of absolute yaw and pitch error in degrees, each
      with its median marked.

Filtering (the loop's own gate, `pvpbot/deploy/loop.py:768` and :830)
      Ticks are kept only when `settled` is true (game frontmost, mouse
      grabbed, grab streak satisfied -- the loop injects nothing otherwise)
      AND `percep[3] > 0.5` (the raw CNN says the enemy is on screen this
      frame, which is the exact gate that arms the aim assist). On those
      ticks `obs[22]` is bit-identical to `percep[0]`, so both axes of the
      left panel are the CNN's own estimate.

No smoothing, no subsampling, no outlier removal: every gated tick in the log
is drawn. The x axis is clipped to +/-60 deg for legibility and the script
prints (and the figure states) what fraction of ticks that clip touches.
Every number in the figure -- the correlation, the medians, the tick count --
is recomputed at render time, because the log is regenerated by live runs.

Run from the repo root:

    python3 tools/figures/fig_camera_control_law.py
    python3 tools/figures/fig_camera_control_law.py --preview /tmp/preview.png
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import re
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from matplotlib.colors import LinearSegmentedColormap, to_rgb  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402
from matplotlib.patches import Patch  # noqa: E402

# --- paths -----------------------------------------------------------------
REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "pvpbot-flight.jsonl"          # gitignored live-run telemetry
LOOP = REPO / "pvpbot" / "deploy" / "loop.py"
OUT = REPO / "docs" / "assets" / "camera-control-law.svg"

sys.path.insert(0, str(REPO))
from pvpbot.spec import CAMERA_BINS, OBS_LAYOUT, PERCEPTION_LAYOUT  # noqa: E402

BINS = np.asarray(CAMERA_BINS, dtype=np.float64)

# --- the control law, transcribed from pvpbot/deploy/loop.py:848-849 -------
#   action[5] = _nearest_bin(float(np.clip(0.7 * err_deg, -25.0, 25.0)))
YAW_GAIN, YAW_CLIP = 0.7, 25.0
#   action[6] = _nearest_bin(float(np.clip(0.65 * pitch_err_deg, -18.0, 18.0)))
PITCH_GAIN, PITCH_CLIP = 0.65, 18.0

# --- palette (the seven diagram hexes; text is mid/dark grey only) ---------
C_LIVE = "#1d5c93"       # live deploy path: the commanded camera delta
C_PERCEPTION = "#a8621b"  # CNN estimate: the pitch histogram
C_LAW = "#9b1c31"        # the analytic law overlay
INK = "#4a4a4a"
GREY = "#8b8b8b"

I_YAW = OBS_LAYOUT["aim_err_yaw"][0]        # 22
I_PITCH = OBS_LAYOUT["aim_err_pitch"][0]    # 23
I_VIS = PERCEPTION_LAYOUT["visible"]        # 3
X_CLIP = 60.0
Y_LIM = 32.0


def nearest_bin(deg: np.ndarray) -> np.ndarray:
    """Vectorized copy of `_nearest_bin` in pvpbot/deploy/loop.py:111-112."""
    return BINS[np.abs(BINS[None, :] - np.asarray(deg)[:, None]).argmin(axis=1)]


def check_law_against_source() -> None:
    """Warn loudly if loop.py no longer contains the transcribed constants."""
    if not LOOP.exists():
        print(f"  ! {LOOP} missing; cannot verify control-law constants")
        return
    src = LOOP.read_text()
    want = [r"0\.7\s*\*\s*err_deg", r"-25\.0,\s*25\.0", r"0\.65\s*\*", r"-18\.0,\s*18\.0"]
    missing = [w for w in want if re.search(w, src) is None]
    if missing:
        print("  ! control law in loop.py no longer matches this script: "
              f"{missing} -- update YAW_GAIN/YAW_CLIP/PITCH_GAIN/PITCH_CLIP")
    else:
        print("  control law constants verified against pvpbot/deploy/loop.py")


def load() -> dict:
    if not DATA.exists():
        sys.exit(
            f"missing data file: {DATA}\n"
            "pvpbot-flight.jsonl is live-run telemetry and is gitignored, so a\n"
            "fresh clone will not have it. Produce one with a live session\n"
            "(python3 -m pvpbot.deploy.run ...), or read the committed SVG at\n"
            f"{OUT.relative_to(REPO)} instead."
        )
    ey, ep, cy, cp, t = [], [], [], [], []
    n_rows = n_settled = 0
    with DATA.open() as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            n_rows += 1
            if not r.get("settled"):
                continue
            n_settled += 1
            if float(r["percep"][I_VIS]) <= 0.5:
                continue
            ey.append(float(r["obs"][I_YAW]) * 180.0)
            ep.append(float(r["obs"][I_PITCH]) * 90.0)
            cy.append(BINS[int(r["action"][5])])
            cp.append(BINS[int(r["action"][6])])
            t.append(float(r["t"]))
    if len(ey) < 100:
        sys.exit(f"only {len(ey)} gated ticks in {DATA}; too few to plot")
    return dict(err_yaw=np.array(ey), err_pitch=np.array(ep),
                cmd_yaw=np.array(cy), cmd_pitch=np.array(cp),
                t=np.array(t), n_rows=n_rows, n_settled=n_settled)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--preview", metavar="PNG",
                    help="also write a transparent raster copy here, for "
                         "eyeballing the result over a light and a dark page")
    args = ap.parse_args()

    check_law_against_source()
    d = load()
    ey, cy, ep, cp = d["err_yaw"], d["cmd_yaw"], d["err_pitch"], d["cmd_pitch"]
    n = ey.size

    # --- statistics, all recomputed at render time -------------------------
    r_yaw = float(np.corrcoef(ey, cy)[0, 1])
    r_pitch = float(np.corrcoef(ep, cp)[0, 1])
    med_yaw = float(np.median(np.abs(ey)))
    med_pitch = float(np.median(np.abs(ep)))
    exact_yaw = float(np.mean(nearest_bin(np.clip(YAW_GAIN * ey, -YAW_CLIP, YAW_CLIP)) == cy))
    exact_pitch = float(np.mean(
        nearest_bin(np.clip(PITCH_GAIN * ep, -PITCH_CLIP, PITCH_CLIP)) == cp))
    # the +/-30 bin wins once the commanded delta passes the 15/30 midpoint,
    # i.e. once 0.7 * err_deg > 22.5
    knee = 0.5 * (BINS[-1] + BINS[-2]) / YAW_GAIN
    frac_sat = float(np.mean(np.abs(ey) > knee))
    frac_off = float(np.mean(np.abs(ey) > X_CLIP))
    dur_min = float(d["t"].max() - d["t"].min()) / 60.0

    print(f"  rows={d['n_rows']}  settled={d['n_settled']}  gated(settled & percep[3]>0.5)={n}")
    print(f"  yaw   r={r_yaw:.4f}  median|err|={med_yaw:.2f} deg  law reproduces {exact_yaw:.1%} of bins")
    print(f"  pitch r={r_pitch:.4f}  median|err|={med_pitch:.2f} deg  law reproduces {exact_pitch:.1%} of bins")
    print(f"  saturated (|err| > {knee:.1f} deg -> +/-30 bin): {frac_sat:.2%}"
          f"   beyond the {X_CLIP:.0f} deg x-clip: {frac_off:.2%}")
    print(f"  log span {dur_min:.1f} min of live ticks")

    # --- figure ------------------------------------------------------------
    fig, (axL, axR) = plt.subplots(
        1, 2, figsize=(11, 3.8), gridspec_kw=dict(width_ratios=[2.45, 1.0], wspace=0.30))
    fig.patch.set_alpha(0.0)
    for ax in (axL, axR):
        ax.set_facecolor("none")
        for sp in ("top", "right"):
            ax.spines[sp].set_visible(False)
        for sp in ("left", "bottom"):
            ax.spines[sp].set_color(GREY)
            ax.spines[sp].set_linewidth(0.8)
        ax.tick_params(colors=INK, labelsize=8, length=3, width=0.8)

    # ---------------- left: error -> commanded bin -------------------------
    for b in BINS:
        axL.axhline(b, color=GREY, alpha=0.30, lw=0.7, zorder=0)
    axL.axvline(0.0, color=GREY, alpha=0.25, lw=0.7, zorder=0)

    rgb = to_rgb(C_LIVE)
    ramp = LinearSegmentedColormap.from_list(
        "live_ramp", [(*rgb, 0.28), (*rgb, 0.65), (*rgb, 1.0)])
    hb = axL.hexbin(np.clip(ey, -X_CLIP, X_CLIP), cy, gridsize=(58, 22),
                    extent=(-X_CLIP, X_CLIP, -Y_LIM, Y_LIM), bins="log",
                    cmap=ramp, mincnt=1, linewidths=0.0, zorder=2)

    xs = np.linspace(-X_CLIP, X_CLIP, 3001)
    law = nearest_bin(np.clip(YAW_GAIN * xs, -YAW_CLIP, YAW_CLIP))
    axL.plot(xs, law, color=C_LAW, lw=1.5, ls=(0, (4.5, 2.5)), zorder=4,
             solid_capstyle="butt")

    axL.set_xlim(-X_CLIP, X_CLIP)
    axL.set_ylim(-Y_LIM, Y_LIM)
    axL.set_xlabel("perceived yaw error to enemy centre (degrees, CNN estimate)",
                   color=INK, fontsize=9)
    axL.set_ylabel("commanded camera delta (deg per 50 ms tick)",
                   color=INK, fontsize=9)
    axL.set_xticks([-60, -40, -20, 0, 20, 40, 60])

    # right-hand axis: the 11 CAMERA_BINS values themselves. The five inner
    # bins sit within 3 deg of each other, so they share one label.
    axB = axL.twinx()
    axB.set_ylim(-Y_LIM, Y_LIM)
    axB.set_facecolor("none")
    for sp in axB.spines.values():
        sp.set_visible(False)
    ticks = [-30.0, -15.0, -7.0, -3.0, 0.0, 3.0, 7.0, 15.0, 30.0]
    labels = ["-30", "-15", "-7", "-3", "0, ±1", "3", "7", "15", "30"]
    axB.set_yticks(ticks)
    axB.set_yticklabels(labels, fontsize=7, color=GREY)
    axB.tick_params(length=0, pad=2)
    axB.set_ylabel("CAMERA_BINS, the 11 legal deltas (deg/tick)",
                   color=GREY, fontsize=8, rotation=270, labelpad=12)

    handles = [
        Patch(facecolor=C_LIVE, alpha=0.85, edgecolor="none",
              label="live ticks (hex shade = count, log)"),
        Line2D([0], [0], color=C_LAW, lw=1.5, ls=(0, (4.5, 2.5)),
               label="nearest bin to clip(0.7 × error, ±25)"),
    ]
    leg = axL.legend(handles=handles, loc="upper left", fontsize=7.6,
                     frameon=False, borderaxespad=0.15, handlelength=1.8,
                     labelspacing=0.35)
    for txt in leg.get_texts():
        txt.set_color(INK)

    axL.text(0.018, 0.775,
             f"r = {r_yaw:.3f} over N = {n:,} visible ticks\n"
             f"the law reproduces {exact_yaw:.1%} of commanded bins\n"
             "pvpbot/deploy/loop.py:848",
             transform=axL.transAxes, ha="left", va="top",
             fontsize=7.4, color=INK, linespacing=1.45)

    axL.annotate(
        f"beyond ±{knee:.0f}° the command\nsaturates at the ±30 bin\n"
        f"({frac_sat:.1%} of ticks)",
        xy=(47.0, 29.0), xytext=(59.0, 8.0), fontsize=7.2, color=INK,
        ha="right", va="center", linespacing=1.4,
        arrowprops=dict(arrowstyle="->", color=GREY, lw=0.8,
                        shrinkA=3, shrinkB=3))
    axL.annotate(
        "|error| < 0.7° → the 0 bin:\nno camera command",
        xy=(0.6, -0.3), xytext=(7.0, -15.0), fontsize=7.2, color=INK,
        ha="left", va="center", linespacing=1.4,
        arrowprops=dict(arrowstyle="->", color=GREY, lw=0.8,
                        shrinkA=3, shrinkB=3))

    axL.text(0.995, 0.075,
             f"error axis clipped to ±{X_CLIP:.0f}° ({frac_off:.2%} of ticks "
             "lie beyond it)",
             transform=axL.transAxes, ha="right", va="bottom",
             fontsize=6.8, color=GREY)

    # ---------------- right: |error| distributions -------------------------
    edges = np.linspace(0.0, X_CLIP, 41)
    axR.hist(np.abs(ey), bins=edges, color=C_LIVE, alpha=0.6, lw=0.0,
             label="yaw")
    axR.hist(np.abs(ep), bins=edges, color=C_PERCEPTION, alpha=0.6, lw=0.0,
             label="pitch")
    top = axR.get_ylim()[1]
    axR.set_ylim(0, top * 1.34)
    axR.axvline(med_yaw, color=C_LIVE, ls=(0, (3, 2)), lw=1.2)
    axR.axvline(med_pitch, color=C_PERCEPTION, ls=(0, (3, 2)), lw=1.2)
    axR.annotate(f"median |yaw| {med_yaw:.1f}°", xy=(med_yaw, top * 1.14),
                 xytext=(med_yaw + 7.0, top * 1.14), fontsize=7.4, color=C_LIVE,
                 va="center", ha="left",
                 arrowprops=dict(arrowstyle="->", color=C_LIVE, lw=0.8,
                                 shrinkA=1, shrinkB=1))
    axR.annotate(f"median |pitch| {med_pitch:.1f}°", xy=(med_pitch, top * 0.94),
                 xytext=(med_pitch + 7.0, top * 0.94), fontsize=7.4,
                 color=C_PERCEPTION, va="center", ha="left",
                 arrowprops=dict(arrowstyle="->", color=C_PERCEPTION, lw=0.8,
                                 shrinkA=1, shrinkB=1))
    axR.set_xlim(0, X_CLIP)
    axR.set_xlabel("absolute aim error (degrees)", color=INK, fontsize=9)
    axR.set_ylabel("ticks", color=INK, fontsize=9)
    axR.grid(axis="y", color=GREY, alpha=0.22, lw=0.7)
    axR.set_axisbelow(True)
    legR = axR.legend(loc="upper right", fontsize=7.4, frameon=False,
                      handlelength=1.2, borderaxespad=0.2)
    for txt in legR.get_texts():
        txt.set_color(INK)

    # ---------------- honesty text + provenance stamp ----------------------
    fig.text(
        0.008, -0.055,
        "Both axes are the CNN's own estimate — this shows what the bot "
        "BELIEVES, not ground truth. The 10.6% → 54.1% M2 progression was "
        "measured against mineflayer ground truth\nand is a different quantity "
        "(docs/07).",
        fontsize=8.0, color=INK, ha="left", va="top", linespacing=1.5)
    fig.text(
        0.008, -0.175,
        f"pvpbot-flight.jsonl, {n:,} settled visible ticks, "
        f"rendered {_dt.date.today().isoformat()}",
        fontsize=7.2, color=GREY, ha="left", va="top", family="monospace")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT, format="svg", transparent=True, bbox_inches="tight")
    if args.preview:
        fig.savefig(args.preview, dpi=170, transparent=True,
                    bbox_inches="tight")
        print(f"  preview -> {args.preview}")
    plt.close(fig)
    print(f"  wrote {OUT}  ({OUT.stat().st_size / 1024:.0f} kB)")


if __name__ == "__main__":
    main()
